[tool.pytest.ini_options]
python_paths = "."

[tool.black]
line-length = 100
target-version = ['py39']
exclude = '(\.vscode|\.venv|venv)'

[tool.isort]
profile = "black"
py_version = 39
force_sort_within_sections = true
skip = ".venv,venv"